server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_test
    username: postgres
    password: "P@ssw0rd()SQL"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


